# A workflow of VICSOLWANG's project

name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        node_version: ['12', '14', '16']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: cache-node_modules
        with:
          path: node_modules
          key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
      - run: node --version
      - run: npm --version   
      - run: npm install
      - run: |
          npm test
          npm run cover:report
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.lcov
      
  codecov:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: coverage
      - uses: codecov/codecov-action@v2
